from tkinter import*
from tkinter import ttk
root=Tk()
root.title("Student Management System")
root.geometry("600x400+0+0")

sc=Scrollbar(root,orient=VERTICAL)
sc.pack(side=RIGHT,fill=Y)

addmissionFrame=Frame(root)
addmissionFrame.pack()

SRegisterId=Label(addmissionFrame,text="Registration Id:",font=("Arial",15,"bold"))
SRegisterId.grid(row=0,column=0,padx=5,pady=10,sticky=W)
SRegisterId=Entry(addmissionFrame,font=("Arial",15,"bold"),width=25)
SRegisterId.grid(row=0,column=1,padx=5,pady=10,sticky=W)
SName=Label(addmissionFrame,text="Student Name:",font=("Arial",15,"bold"))
SName.grid(row=1,column=0,padx=5,pady=10,sticky=W)
SName=Entry(addmissionFrame,font=("Arial",15,"bold"),width=25)
SName.grid(row=1,column=1,padx=5,pady=10,sticky=W)
SRoll=Label(addmissionFrame,text="Roll:",font=("Arial",15,"bold"))
SRoll.grid(row=2,column=0,padx=5,pady=10,sticky=W)
SRoll=Entry(addmissionFrame,font=("Arial",15,"bold"),width=25)
SRoll.grid(row=2,column=1,padx=5,pady=10,sticky=W)
SSubject=Label(addmissionFrame,text="Subject:",font=("Arial",15,"bold"))
SSubject.grid(row=3,column=0,padx=5,pady=10,sticky=W)
SSubject=Entry(addmissionFrame,font=("Arial",15,"bold"),width=25)
SSubject.grid(row=3,column=1,padx=5,pady=10,sticky=W)
SEmail=Label(addmissionFrame,text="Student Email:",font=("Arial",15,"bold"))
SEmail.grid(row=4,column=0,padx=5,pady=10,sticky=W)
SEmailEn=Entry(addmissionFrame,font=("Arial",15,"bold"),width=25)
SEmailEn.grid(row=4,column=1,padx=5,pady=10,sticky=W)
SDob=Label(addmissionFrame,text="Dob:",font=("Arial",15,"bold"))
SDob.grid(row=5,column=0,padx=5,pady=10,sticky=W)
SDobEn=Entry(addmissionFrame,font=("Arial",15,"bold"),width=25)
SDobEn.grid(row=5,column=1,padx=5,pady=10,sticky=W)
SState=Label(addmissionFrame,text="State:",font=("Arial",15,"bold"))
SState.grid(row=6,column=0,padx=5,pady=10,sticky=W)
SStateEn=Entry(addmissionFrame,font=("Arial",15,"bold"),width=25)
SStateEn.grid(row=6,column=1,padx=5,pady=10,sticky=W)
SDistrict=Label(addmissionFrame,text="District:",font=("Arial",15,"bold"))
SDistrict.grid(row=7,column=0,padx=5,pady=10,sticky=W)
SDistrictEn=Entry(addmissionFrame,font=("Arial",15,"bold"),width=25)
SDistrictEn.grid(row=7,column=1,padx=5,pady=10,sticky=W)
SGender=Label(addmissionFrame,text="Gender:",font=("Arial",15,"bold"))
SGender.grid(row=8,column=0,sticky=W)    
SGenderBox=ttk.Combobox(addmissionFrame,font=("Arial",12,"bold"),state="readonly",width=8)
SGenderBox["value"]=("Male","Female","Transgender")
SGenderBox.current(0)
SGenderBox.grid(row=9,column=1,padx=5,pady=10,sticky=W)
SCaste=Label(addmissionFrame,text="Caste:",font=("Arial",15,"bold"))
SCaste.grid(row=10,column=0,padx=5,pady=10,sticky=W)
SCasteEn=Entry(addmissionFrame,font=("Arial",15,"bold"),width=25)
SCasteEn.grid(row=10,column=1,padx=5,pady=10,sticky=W)
SNationality=Label(addmissionFrame,text="Nationality:",font=("Arial",15,"bold"))
SNationality.grid(row=10,column=0,padx=5,pady=10,sticky=W)
SNationalityEn=Entry(addmissionFrame,font=("Arial",15,"bold"),width=25)
SNationalityEn.grid(row=10,column=1,padx=5,pady=10,sticky=W)
SNumber=Label(addmissionFrame,text="Mobile No:",font=("Arial",15,"bold"))
SNumber.grid(row=11,column=0,padx=5,pady=10,sticky=W)
SNumberEn=Entry(addmissionFrame,font=("Arial",15,"bold"),width=25)
SNumberEn.grid(row=11,column=1,padx=5,pady=10,sticky=W)

Ssubmit=Button(addmissionFrame,text="Submit Now!",font=("Arial",20,"bold"))
Ssubmit.grid(row=12,column=0,columnspan=2,padx=5,pady=10,sticky=W)


root.mainloop()